#dockerfile for QUOTESERVICE


FROM python:3.8-slim
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir flask pymongo redis
EXPOSE 5000
ENV FLASK_APP=main.py


CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
