stages:
  - lint
  - test
  - build
  - deploy

# Lint Stage

lint:
  stage: lint
  image: python:3.10
  script:
    - pip install pylint flask pymongo redis
    - pylint QuoteService/main.py
  only:
    - main

# Test Stage
test:
  stage: test
  image: python:3.10
  script:
    - pip install pytest flask pymongo redis
    - pytest tests/ --maxfail=5 --disable-warnings
  only:
    - main

# Build Stage
build:
  stage: build
  image: docker:24
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker-compose -f docker-compose.yml build
  only:
    - main

# Deploy Stage
deploy:
  stage: deploy
  image: docker:24
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker-compose -f docker-compose.yml up -d
  only:
    - main
